### ISSUE TITLE
Suggestion: Change compileClasspath to runtimeClasspath in build.gradle

### ISSUE THREAD

**Issue by nspsck** [libgdx/gdx-liftoff#212]
Hi! I am trying to use the latest `.jar` file to test out `libgdx` on an raspberry pi using debian bookworm on wayland. Everything works fine until I click on the `PROJECT PATH` field, which crashes the tool with the following message:

```
java -jar gdx-liftoff-1.13.0.1.jar 
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[NFD] The Native File Dialog library could not be loaded.
Check if you have multiple LWJGL3 applications open simultaneously,
since that can cause this error.
[NFD] java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl_nfd.so
Exception in thread "main" java.lang.RuntimeException: Actor: TextButton: 
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:192)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:125)
	at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:93)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:71)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:354)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:70)
	at com.badlogic.gdx.backends.lwjgl3.DefaultLwjgl3Input.update(DefaultLwjgl3Input.java:189)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:378)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:193)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:167)
	at gdx.liftoff.Main.main(Main.java:205)
Caused by: java.lang.IllegalStateException: VisUI is not loaded!
	at com.kotcrab.vis.ui.VisUI.getSkin(VisUI.java:122)
	at com.kotcrab.vis.ui.widget.VisWindow.<init>(VisWindow.java:52)
	at com.kotcrab.vis.ui.widget.VisWindow.<init>(VisWindow.java:47)
	at com.kotcrab.vis.ui.widget.file.FileChooser.<init>(FileChooser.java:172)
	at com.kotcrab.vis.ui.widget.file.FileChooser.<init>(FileChooser.java:164)
	at gdx.liftoff.Main.pickDirectory(Main.java:464)
	at gdx.liftoff.ui.panels.PathsPanel.lambda$populate$0(PathsPanel.java:50)
	at gdx.liftoff.Main$2.changed(Main.java:297)
	at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
```
After doing some research on the internet, I came across [this post](https://stackoverflow.com/questions/70584147/failed-to-load-library-liblwjgl-so), which hints that [this line](https://github.com/libgdx/gdx-liftoff/blob/42dd92ba2d271eb0e1d490ab68fc19c5ddcee8f0/build.gradle#L46) in `build.gradle` is probably causing the problem for me. Would there be any downsides if we change `compileClasspath` to `runtimeClasspath`?

Best Regards

**Comment by tommyettinger** [comment]
I think the problem may be simpler than that -- the Liftoff build.gradle script included natives for Native File Dialog on Linux, but only for x64 Linux (almost all desktops, but not devices like Raspberry Pi-s). I've attached a quick build that didn't change compileClasspath, but did add dependencies on the ARM32 and ARM64 NFD natives, which now matches what we depend on from the rest of LWJGL3. If you could try it out and try to pick a project path with the file picker, that would help a lot.

[gdx-liftoff-1.13.0.2-SNAPSHOT.jar.zip](https://github.com/user-attachments/files/18002588/gdx-liftoff-1.13.0.2-SNAPSHOT.jar.zip)

**Comment by tommyettinger** [comment]
Great! I should be able to push a release soon, I just need to figure out if I can use 1.13.0 yet or not. I need some way to remove the LWJGL3 x86 Windows DLLs, since those cause antivirus to freak out for some reason. I have a decent way now, that might work in user projects... I would also probably need a solution for GWT's broken SpriteBatch and probably other similar issues, like the (untested?) CpuSpriteBatch...

Or I could do another 1.12.1 release right away.
